### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by AwaitingIrindul** [PolytechLyon/isi3-singleton-regnard-marchand-tp5#2]
Bonjour, 

Peut on avoir une code review por favor ? 😄

**Comment by Slashgear** [comment]
- je suis pas satisfait de votre description de l'autowiring. C'est quoi en fait ? On peut le faire en XML si oui comment 

- 💡 Spring Profil

**Comment by AwaitingIrindul** [comment]
- L'autowiring va permettre de spécifier à Spring qu'un bean doit être injecté dans un composant grâce à a l'annotation `@Autowired`, Spring va ensuite résoudre et injcter le bon bean. Il est possible de le faire en XML en utilisant l'attribut `autowire` de la balise `<bean>`. Cet attribut possède différentes options : 
    - `autowire="byName"`, Spring va chercher un bean ayant le même nom que la property d'autres beans, et va injecter le premier bean dans les autres.
    - `autowire="byType"`, Spring va chercher un bean ayant le même type que la property d'autres bean et va injecter le premier bean dans les autres.
   - `autowire="constructor"`, Spring va chercher un bean ayant le même type que les arguments du constructeur d'un autre bean et va injecter le premier dans les autres.

Si cette définition vous va plus, je l'updaterai dans le rapport :)

- [x] Spring profile done

**Comment by Slashgear** [comment]
👌
